name: Typecheck

on:
  # Run this workflow on push to main
  push:
    branches:
      - main

  # Run this workflow on pull request to main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)

    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - name: Install dependencies
        run: pnpm install

      - name: Run type-check validation
        run: pnpm run type-check
